/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_progames723_hmmm_GMP */

#ifndef _Included_dev_progames723_hmmm_GMP
#define _Included_dev_progames723_hmmm_GMP
#ifdef __cplusplus
extern "C" {
#endif
#undef dev_progames723_hmmm_GMP_serialVersionUID
#define dev_progames723_hmmm_GMP_serialVersionUID -8742448824652078965i64
/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    intValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_progames723_hmmm_GMP_intValue(JNIEnv *, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    longValue
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dev_progames723_hmmm_GMP_longValue(JNIEnv *, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    floatValue
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_dev_progames723_hmmm_GMP_floatValue(JNIEnv *, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    doubleValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_dev_progames723_hmmm_GMP_doubleValue(JNIEnv *, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    getAsString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_progames723_hmmm_GMP_getAsString(JNIEnv *, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    create
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_dev_progames723_hmmm_GMP_create__D(JNIEnv *, jobject, jdouble);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    create
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dev_progames723_hmmm_GMP_create__Ljava_lang_String_2(JNIEnv *, jobject, jstring);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    multiply
 * Signature: (Ldev/progames723/hmmm/GMP;)Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_multiply__Ldev_progames723_hmmm_GMP_2(JNIEnv *, jobject, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    multiply
 * Signature: (Ljava/lang/String;)Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_multiply__Ljava_lang_String_2(JNIEnv *, jobject, jstring);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    divide
 * Signature: (Ldev/progames723/hmmm/GMP;)Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_divide__Ldev_progames723_hmmm_GMP_2(JNIEnv *, jobject, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    divide
 * Signature: (Ljava/lang/String;)Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_divide__Ljava_lang_String_2(JNIEnv *, jobject, jstring);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    pow
 * Signature: (Ldev/progames723/hmmm/GMP;)Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_pow__Ldev_progames723_hmmm_GMP_2(JNIEnv *, jobject, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    pow
 * Signature: (Ljava/lang/String;)Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_pow__Ljava_lang_String_2(JNIEnv *, jobject, jstring);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    sqrt
 * Signature: ()Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_sqrt(JNIEnv *, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    add
 * Signature: (Ldev/progames723/hmmm/GMP;)Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_add__Ldev_progames723_hmmm_GMP_2(JNIEnv *, jobject, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    add
 * Signature: (Ljava/lang/String;)Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_add__Ljava_lang_String_2(JNIEnv *, jobject, jstring);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    subtract
 * Signature: (Ldev/progames723/hmmm/GMP;)Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_subtract__Ldev_progames723_hmmm_GMP_2(JNIEnv *, jobject, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    subtract
 * Signature: (Ljava/lang/String;)Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_subtract__Ljava_lang_String_2(JNIEnv *, jobject, jstring);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    ceil
 * Signature: ()Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_ceil(JNIEnv *, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    floor
 * Signature: ()Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_floor(JNIEnv *, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    abs
 * Signature: ()Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_abs(JNIEnv *, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    truncate
 * Signature: ()Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_truncate(JNIEnv *, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_progames723_hmmm_GMP_clear(JNIEnv *, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    set
 * Signature: (Ldev/progames723/hmmm/GMP;)Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_set__Ldev_progames723_hmmm_GMP_2(JNIEnv *, jobject, jobject);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    set
 * Signature: (Ljava/lang/String;)Ldev/progames723/hmmm/GMP;
 */
JNIEXPORT jobject JNICALL Java_dev_progames723_hmmm_GMP_set__Ljava_lang_String_2(JNIEnv *, jobject, jstring);

/*
 * Class:     dev_progames723_hmmm_GMP
 * Method:    equals
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_progames723_hmmm_GMP_equals(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
