/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_progames723_hmmm_utils_NativeReflectUtil_Primitives */

#ifndef _Included_dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
#define _Included_dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    registerNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_progames723_hmmm_utils_NativeReflectUtil_00024Primitives_registerNatives(JNIEnv *env, jclass cls);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    getIntField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL getIntField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    setIntField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL setIntField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance, jint value);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    getLongField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL getLongField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    setLongField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;J)V
 */
JNIEXPORT void JNICALL setLongField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance, jlong value);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    getFloatField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)F
 */
JNIEXPORT jfloat JNICALL getFloatField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    setFloatField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;F)V
 */
JNIEXPORT void JNICALL setFloatField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance, jfloat value);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    getDoubleField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)D
 */
JNIEXPORT jdouble JNICALL getDoubleField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    setDoubleField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;D)V
 */
JNIEXPORT void JNICALL setDoubleField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance, jdouble value);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    getShortField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)S
 */
JNIEXPORT jshort JNICALL getShortField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    setShortField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;S)V
 */
JNIEXPORT void JNICALL setShortField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance, jshort value);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    getByteField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)B
 */
JNIEXPORT jbyte JNICALL getByteField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    setByteField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;B)V
 */
JNIEXPORT void JNICALL setByteField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance, jbyte value);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    getCharField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)C
 */
JNIEXPORT jchar JNICALL getCharField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    setCharField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;C)V
 */
JNIEXPORT void JNICALL setCharField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance, jchar value);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    getBooleanField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL getBooleanField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance);

/*
 * Class:     dev_progames723_hmmm_utils_NativeReflectUtil_Primitives
 * Method:    setBooleanField0
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;Z)V
 */
JNIEXPORT void JNICALL setBooleanField0(JNIEnv *env, jclass cls, jstring fieldName, jclass clazz, jobject objectInstance, jboolean value);

#ifdef __cplusplus
}
#endif
#endif
