/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_progames723_hmmm_utils_MathUtil */

#ifndef _Included_dev_progames723_hmmm_utils_MathUtil
#define _Included_dev_progames723_hmmm_utils_MathUtil
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     dev_progames723_hmmm_utils_MathUtil
 * Method:    registerNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_progames723_hmmm_utils_MathUtil_registerNatives(JNIEnv *, jclass);

/*
 * Class:     dev_progames723_hmmm_utils_MathUtil
 * Method:    fastSqrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL fastSqrt(JNIEnv *, jclass, jdouble);

/*
 * Class:     dev_progames723_hmmm_utils_MathUtil
 * Method:    fastInvSqrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL dFastInvSqrt(JNIEnv *, jclass, jdouble);

/*
 * Class:     dev_progames723_hmmm_utils_MathUtil
 * Method:    fastInvSqrt
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL fFastInvSqrt(JNIEnv *, jclass, jfloat);

/*
 * Class:     dev_progames723_hmmm_utils_MathUtil
 * Method:    fastPow
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL fastPow(JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     dev_progames723_hmmm_utils_MathUtil
 * Method:    nthRoot
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL nthRoot(JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
