name: Build native libraries

on:
  workflow_dispatch:
  push:
    paths: ["nativeLibSrc/**"]
  pull_request:
    types: [ opened, reopened, synchronize, edited, ready_for_review, review_requested ]
    paths: ["nativeLibSrc/**"]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            clang
            gmp-devel
            mpfr-devel
            make
            awk
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - uses: actions/checkout@v4
      - name: Build
        shell: msys2 {0}
        run: |
          cd nativeLibSrc
          make -f ./Makefile.win.mk
          make -f ./Makefile.win.mk
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hmmm-native-windows
          path: ./nativeLibSrc/*.dll
          retention-days: 7
          compression-level: 9
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - run: |
          sudo apt update
          sudo apt install gcc
          sudo apt install libgmp10
          sudo apt install libmpfr-dev libmpfr-doc
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd nativeLibSrc
          make -f ./Makefile.linux.mk
          make -f ./Makefile.linux.mk
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hmmm-native-linux
          path: ./nativeLibSrc/lib*.so
          retention-days: 7
          compression-level: 9