name: Build Mod Jar's

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    types: [ opened, reopened, synchronize, edited, ready_for_review, review_requested ]

jobs:
  build_fabric:
    runs-on: ubuntu-latest
    if: ${{ always() && hashFiles('**/fabric/build.gradle') != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew :fabric:build --no-daemon
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hmmm-fabric-DEV
          path: ./fabric/build/libs/*.jar
          retention-days: 7
          compression-level: 9
  build_quilt:
    runs-on: ubuntu-latest
    if: ${{ always() && hashFiles('**/quilt/build.gradle') != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew :quilt:build --no-daemon
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hmmm-fabric-DEV
          path: ./quilt/build/libs/*.jar
          retention-days: 7
          compression-level: 9
  build_forge:
    runs-on: ubuntu-latest
    if: ${{ always() && hashFiles('**/forge/build.gradle') != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew :forge:build --no-daemon
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hmmm-forge-DEV
          path: ./forge/build/libs/*.jar
          retention-days: 7
          compression-level: 9
  build_neoforge:
    if: ${{ always() && hashFiles('**/neoforge/build.gradle') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew :neoforge:build --no-daemon
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hmmm-neoforge-DEV
          path: ./neoforge/build/libs/*.jar
          retention-days: 7
          compression-level: 9